---
- name: Install tools
  package:
    name:
      - netfilter-persistent
      - iptables-persistent
    state: present

- name: Set required sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop: "{{ sysctl_config | dict2items }}"
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.accept_redirects: 0
      net.ipv4.conf.all.send_redirects: 0
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1

- name: set firewall rules for NAT
  set_fact:
    firewall_additional_rules: "{{ firewall_additional_rules | default('[]') }} + ['iptables -A FORWARD -s {{ item }} -j ACCEPT'] + ['iptables -A POSTROUTING -s {{ item }} -j MASQUERADE']"
  with_items: "{{ vpn_gateway_configs[0].local.networks }} + {{ vpn_gateway_configs[0].remote.networks }}"

- name: Activate firewall rules
  vars:
    firewall_state: started
    firewall_enabled_at_boot: true
    firewall_disable_firewalld: true
    firewall_disable_ufw: true
    firewall_enable_ipv6: false
    firewall_flush_rules_and_chains: false
    firewall_log_dropped_packets: false
    firewall_allowed_tcp_ports:
      - "22"
    firewall_allowed_udp_ports: []
  include_role:
      name: geerlingguy.firewall
