---
lint:
  name: yamllint

driver:
  name: hetznercloud
  ssh_connection_options:
    - '-o ControlPath=~/.ansible/cp/%r@%h-%p'
    - '-o IdentitiesOnly=yes'
    - '-o StrictHostKeyChecking=no'

platforms:
  - name: debian9stretch
    server_type: cx11
    image: debian-9
    groups:
      - platforms
  - name: debian10buster
    server_type: cx11
    image: debian-10
    groups:
      - platforms
  - name: ubuntu16
    server_type: cx11
    image: ubuntu-16.04
    groups:
      - platforms
  - name: ubuntu18
    server_type: cx11
    image: ubuntu-18.04
    groups:
      - platforms

provisioner:
  name: ansible
  config_options:
    ssh_connection:
      pipelining: True
  inventory:
    group_vars:
      all:
        vpn_gateway_configs:
          - name: default
            psk: secret
            local:
              public: 1.1.1.1
              private: 172.4.0.20
              private_interface: eth6
              networks:
                - 172.4.0.0/21
            remote:
              public: 1.2.3.4
              networks:
                - 172.240.0.0/21
                - 10.2.0.0/16
  lint:
    name: ansible-lint
  playbooks:
    create: ../resources/playbooks/create.yml
    destroy: ../resources/playbooks/destroy.yml

verifier:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
